// Verification Gates A and B (design-notes point 15) — an independent
// Claude pass that checks MCQ items generated by lessonMaterialGenerator
// for two specific failure modes that string-matching can't catch:
//
//   Gate A: for each option (including distractors), is there a way to
//   argue it's the correct answer using only what the stem/figure actually
//   states? Exactly one option should survive that test — if more than one
//   does (or none do), the stem is missing a property that would rule the
//   others out.
//
//   Gate B: for each distractor whose explanation cites a documented
//   Misconception (an [in-misc-...] tag), does that misconception's error
//   pattern, applied to the actual numbers in this stem, actually produce
//   the exact value shown for that option — not a different one?
//
// This requires real reasoning about the specific numbers in each item, so
// it's a Claude call, not a regex.

import { getMisconceptionsByIds } from './knowledgeGraph.js';

const MCQ_MARKER_RE = /\([A-D]\)/g;
const MISCONCEPTION_TAG_RE = /\[in-misc-[a-z0-9-]+\]/gi;

const SYSTEM_PROMPT = `You are checking multiple-choice items from a generated lesson worksheet for two specific defects. For each item you're given, apply both gates below and report the result — do not fix anything you aren't asked to via corrected_item_text, and do not flag style or wording issues that aren't one of these two gates.

GATE A — every distractor must be beatable using only the stem:
For each option in the item (including the correct answer and every distractor), state the strongest case a student could make that it's the correct answer, using only information actually given in the stem or figure — no outside assumptions. Exactly one option should survive this test as genuinely correct. If more than one option can be defended as correct, or if none can, the stem is missing a named property (a specific number, unit, shape property, or constraint) that would rule the others out — that is a Gate A failure.

GATE B — a cited misconception must actually produce the value shown:
Some distractors' explanations cite a documented Misconception (shown to you below with its error_pattern_en / produces_choice_pattern). For each such distractor, work through that misconception's described error pattern using the actual numbers in this item's stem, and check whether it actually produces the exact value shown for that option. If the misconception's reasoning would produce a different number than what the option displays, that is a Gate B failure — the citation is wrong for these specific numbers, even if the misconception itself is real and well-documented.

An item passes only if it has no Gate A failure AND no Gate B failure (an item with no misconception citations to check automatically passes Gate B).

When an item fails either gate and you can see a concrete fix (e.g. changing one option's value, or adding a missing constraint to the stem), write the full corrected item text in corrected_item_text. Leave corrected_item_text null if the item passed both gates, or if it failed but you can't produce a safe concrete fix.

Do the gate-by-gate reasoning for every option silently, in your head — do not write it out. Your entire response must be nothing but the final JSON object: no headings, no step-by-step analysis, no markdown fences, no text before or after it. Respond with ONLY valid JSON matching exactly this shape:
{
  "all_passed": boolean,
  "items": [
    {
      "item_text": string,
      "gate_a_pass": boolean,
      "gate_b_pass": boolean,
      "issue": string|null,
      "corrected_item_text": string|null
    }
  ]
}
Include exactly one entry in "items" per item you were given, in the same order, with item_text copied verbatim from the input.`;

function looksLikeMcq(itemText) {
  const matches = itemText.match(MCQ_MARKER_RE);
  return !!matches && matches.length >= 2;
}

function extractMisconceptionIds(itemText) {
  const matches = itemText.match(MISCONCEPTION_TAG_RE) || [];
  return matches.map((tag) => tag.slice(1, -1));
}

function buildUserMessage(mcqItems, misconceptionsById) {
  const lines = ['Check the following MCQ items.', ''];

  mcqItems.forEach((itemText, index) => {
    lines.push(`ITEM ${index + 1}:`, itemText, '');

    const ids = extractMisconceptionIds(itemText);
    if (ids.length > 0) {
      lines.push('Misconceptions cited in this item:');
      for (const id of ids) {
        const record = misconceptionsById.get(id);
        if (record) {
          lines.push(
            `- [${id}] ${record.error_pattern_en}` +
              (record.produces_choice_pattern ? ` (produces_choice_pattern: ${record.produces_choice_pattern})` : '')
          );
        } else {
          lines.push(`- [${id}] (no matching Misconception record found — treat this citation as unverifiable)`);
        }
      }
      lines.push('');
    }
  });

  return lines.join('\n');
}

/**
 * Scans lesson_json.student_sections for MCQ-shaped items and runs
 * Verification Gates A and B against them via Claude. Applies any
 * corrected_item_text back into lesson_json in place.
 *
 * @param {object} lesson_json
 * @returns {Promise<
 *   { checked: false, lesson_json: object }
 *   | { checked: true, all_passed: boolean, issues_found: number, lesson_json: object }
 * >}
 */
export async function verifyMcqSections(lesson_json) {
  const sections = lesson_json?.student_sections || [];
  const mcqItems = [];
  for (const section of sections) {
    for (const item of section.items || []) {
      if (typeof item === 'string' && looksLikeMcq(item)) {
        mcqItems.push(item);
      }
    }
  }

  if (mcqItems.length === 0) {
    return { checked: false, lesson_json };
  }

  const allIds = new Set();
  for (const item of mcqItems) {
    for (const id of extractMisconceptionIds(item)) allIds.add(id);
  }
  const misconceptionRecords = await getMisconceptionsByIds([...allIds]);
  const misconceptionsById = new Map(misconceptionRecords.map((r) => [r.id, r]));

  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error('ANTHROPIC_API_KEY is not set');
  }

  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': process.env.ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-6',
      max_tokens: 4000,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: buildUserMessage(mcqItems, misconceptionsById) }]
    })
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Claude API returned an error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const rawFull = data.content?.[0]?.text || '';
  let raw = rawFull.trim();

  // Defensive: the prompt insists on JSON-only, but a model sometimes wraps
  // it in a fence or adds reasoning text anyway (long, multi-step gate
  // reasoning makes that more likely than the shorter generator prompt) —
  // pull the fenced block if present, else the outermost {...} object.
  const fenceMatch = raw.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (fenceMatch) {
    raw = fenceMatch[1];
  } else {
    const firstBrace = raw.indexOf('{');
    const lastBrace = raw.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace > firstBrace) {
      raw = raw.slice(firstBrace, lastBrace + 1);
    }
  }

  let verification;
  try {
    verification = JSON.parse(raw);
  } catch (parseErr) {
    throw new Error(`Could not parse verification JSON from Claude's response: ${parseErr.message}. Raw response: ${rawFull}`);
  }

  const corrections = new Map();
  let issuesFound = 0;
  for (const result of verification.items || []) {
    const failed = !result.gate_a_pass || !result.gate_b_pass;
    if (failed) issuesFound += 1;
    if (failed && result.corrected_item_text) {
      corrections.set(result.item_text, result.corrected_item_text);
    }
  }

  if (corrections.size > 0) {
    for (const section of sections) {
      if (!Array.isArray(section.items)) continue;
      section.items = section.items.map((item) =>
        typeof item === 'string' && corrections.has(item) ? corrections.get(item) : item
      );
    }
  }

  return {
    checked: true,
    all_passed: !!verification.all_passed,
    issues_found: issuesFound,
    details: verification.items || [],
    lesson_json
  };
}
